#!/bin/ksh

#

openbsd_base_url='http://mirror.ox.ac.uk/pub/OpenBSD'
openbsd_platform=`machine -a`
openbsd_version=`uname -r`
package_specs='
  curl
  emacs-24.3-no_x11
  nginx-1.5.0
  node
  python-2.7.5
  python-3.3.2
  rsync-3.0.9p3
  ruby-2.0.0.247
  sqlports
  wget
'
ports_local_path='/tmp/ports.tar.gz'

#

openbsd_version_base_url="${openbsd_base_url}/${openbsd_version}"

#

ports_url="${openbsd_version_base_url}/ports.tar.gz"
packages_base_url="${openbsd_version_base_url}/packages/${openbsd_platform}"

#

export PKG_PATH="$packages_base_url"

#

for package_spec in $package_specs; do
  cat <<EOF 1>&2
# Installing "$package_spec" from $PKG_PATH
EOF
  pkg_add $package_spec
done

#

if test -d /usr/ports; then
  cat <<EOF 1>&2
# Ports tree already installed
EOF
else
  cat <<EOF 1>&2
# Installing ports from $ports_url
EOF
  cd /tmp
  wget -c -O $ports_local_path $ports_url
  cd /usr
  tar xzf $ports_local_path
  rm -f $ports_local_path
fi

#
