#!/bin/ksh
#________________________________________
# Date created:			11 Nov. 2013
# Description:			Bootstrap an OpenBSD host
#

#________________________________________
# Define global parameters
#

#

openbsd_base_url='http://mirror.ox.ac.uk/pub/OpenBSD'
openbsd_platform=`machine -a`
openbsd_version=`uname -r`
package_specs='
  curl
  emacs-24.3-no_x11
  rsync-3.0.9p3
  git
  nginx-1.5.0
  node
  python-2.7.5
  python-3.3.2
  ruby-2.0.0.247
  wget
'
ports_local_path='/tmp/ports.tar.gz'

#

openbsd_version_base_url="${openbsd_base_url}/${openbsd_version}"

#

ports_url="${openbsd_version_base_url}/ports.tar.gz"
packages_base_url="${openbsd_version_base_url}/packages/${openbsd_platform}"

#

#________________________________________
# Define functions
#

#
# Execute application
#

function execute_application {

  #
  # Set the executable path
  # Set the package path
  #

  export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
  export PKG_PATH="$packages_base_url"

  #
  # Install packages
  # Install ports
  # Install Chef
  #

  install_packages
#DISABLED#  install_ports
  install_chef

}

#
# Install Chef
#

function install_chef {

  cat <<EOF 1>&2
# Installing Chef
EOF
  gem20 install --no-rdoc --no-ri chef

}

#
# Install packages
#

function install_packages {

  for package_spec in $package_specs; do
    cat <<EOF 1>&2
# Installing "$package_spec" from $PKG_PATH
EOF
    pkg_add $package_spec
  done

}

#
# Install ports
#

function install_ports {

  if test -d /usr/ports; then
    cat <<EOF 1>&2
# Ports tree already installed
EOF
  else
    cat <<EOF 1>&2
# Downloading ports from $ports_url
EOF
    cd /tmp
    wget -c -O $ports_local_path $ports_url
    cat <<EOF 1>&2
# Installing ports
EOF
    cd /usr
    tar xzf $ports_local_path
    rm -f $ports_local_path
  fi

}

#________________________________________
# Execute application
#

execute_application $*

#
